spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:/launcher/, file:./launcher/

server:
  port: 8888

info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"